### ISSUE TITLE
Attempt to call global "configCallback"

### ISSUE THREAD

**Issue by pquerner** [blooblahguy/bdTooltips#2]
1x bdTooltips\core.lua:14: attempt to call global 'configCallback' (a nil value)
bdTooltips\core.lua:14: in function `callback'
bdCore\config\config.lua:1112: in function <bdCore\config\config.lua:1104>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'configCallback' (a nil value)"

**Comment by gladelynch** [comment]
Fixed in the next build, thanks
