### ISSUE TITLE
Can't turnoff "eanble mini name hover tooltips".

### ISSUE THREAD

**Issue by Falloutking** [blooblahguy/bdTooltips#4]
When trying to disable the mouseover names in /bd config I get this error message.

Message: Interface\AddOns\bdTooltips\core.lua:14: attempt to call global 'configCallback' (a nil value)
Time: 01/19/18 22:45:26
Count: 3
Stack: Interface\AddOns\bdTooltips\core.lua:14: attempt to call global 'configCallback' (a nil value)
[C]: in function `configCallback'
Interface\AddOns\bdTooltips\core.lua:14: in function `callback'
Interface\AddOns\bdCore\config\config.lua:1116: in function <Interface\AddOns\bdCore\config\config.lua:1108>

Locals: 

Also when trying setting this to false nothing happens as well.

defaults[#defaults+1] = {mott = {
	type = "checkbox",
	value = true,
	label = "Eanble mini name hover tooltips",
	callback = function() configCallback() end

I was able to fix the spelling of enable so I know I'm doing something right. 

![wowscrnshot_011918_224804](https://user-images.githubusercontent.com/35621953/35180749-ec4434d0-fd6a-11e7-8197-572b4f28faa6.jpg)

**Comment by gladelynch** [comment]
This, plus so much more should be officially fixed in the latest bdTooltips :)
