### ISSUE TITLE
Mana wrong

### ISSUE THREAD

**Issue by pquerner** [blooblahguy/bdTooltips#5]
![image](https://user-images.githubusercontent.com/4364044/39401744-1fe396d4-4b4d-11e8-8a2d-8d46b138ffb5.png)

**Comment by gladelynch** [comment]
This should have been fixed back then, sorry for slow reply

**Comment by pquerner** [comment]
Where did you fix it? Its just that I want to learn how it got fixed, because I tried fixing it back then for about 30 minutes but couldnt get it to work.

**Comment by gladelynch** [comment]
I can't remember the exact commit, but I believe I had just changed:

MANA_COST = "**%d** |CFF3399FFMana|r"
to: 
MANA_COST = "**%s** |CFF3399FFMana|r"

The %d version was an older wow build

**Comment by pquerner** [comment]
wow.. I assumed %d would mean decimals or numbers and that it would be fine.

**Comment by gladelynch** [comment]
Right? But I believe since they added comma separated values it became a string instead.
